export const cardOne = [
  {
    title: "Stay 10 nights and get 1 bonus night.",
    img: "/Images/hotels/himalaya.jpg",
    text: "Search for accommodations",
  },
  {
    title:
      "Plans can change. Book a stay with the option to cancel at any time.",
    img: "/Images/hotels/noida.webp",
    text: "Book Now",
  },
  {
    title: "Compare hotels side by side to find the right one for you",
    img: "/Images/hotels/mumbai.jpg",
    text: "Compare hotels",
  },
];

export const slider = [
  [
    "/Images/hotels/himalaya.jpg",
    "/Images/hotels/new-york.avif",
    "/Images/hotels/lumpura-malayisa.jpg",
  ],
  [
    "/Images/hotels/himalaya.jpg",
    "/Images/hotels/new-york.avif",
    "/Images/hotels/lumpura-malayisa.jpg",
  ],
];
export const hotelData = [
  {
    images: [
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],
    name: "ExpoMart Inn",
    location: "Greater Noida",
    rating: 10,
    reviews: 17,
    label: "Exceptional",
    originalPrice: 487,
    currentPrice: 366,
    discount: "25% off",
    perNight: 183,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/Copenhagen.webp",
      "/Images/hotels/Copenhagen1.jpg",
      "/Images/hotels/Copenhagen2.jpg",
      "/Images/hotels/Copenhagen3.jpg",
    ],

    name: "City Comfort Stay",
    location: "Copenhagen",
    rating: 9.2,
    reviews: 42,
    label: "Excellent",
    originalPrice: 620,
    currentPrice: 465,
    discount: "25% off",
    perNight: 232,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/Aarhus.jpg",
      "/Images/hotels/Aarhus1.jpg",
      "/Images/hotels/Aarhus2.jpg",
      "/Images/hotels/Aarhus3.jpg",
    ],

    name: "Nordic Breeze Hotel",
    location: "Aarhus",
    rating: 8.8,
    reviews: 55,
    label: "Very Good",
    originalPrice: 540,
    currentPrice: 459,
    discount: "15% off",
    perNight: 229,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/Odense.jpg",
      "/Images/hotels/Odense1.jpg",
      "/Images/hotels/Odense2.jpg",
      "/Images/hotels/noida3.webp",
    ],

    name: "Urban Nest Suites",
    location: "Odense",
    rating: 9.5,
    reviews: 28,
    label: "Exceptional",
    originalPrice: 700,
    currentPrice: 595,
    discount: "15% off",
    perNight: 298,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/Esbjerg3.jpg",
      "/Images/hotels/Esbjerg.jpg",
      "/Images/hotels/Esbjerg2.jpg",
      "/Images/hotels/Esbjerg1.jpg",
    ],

    name: "Harbor Lights Inn",
    location: "Esbjerg",
    rating: 8.6,
    reviews: 33,
    label: "Very Good",
    originalPrice: 499,
    currentPrice: 374,
    discount: "25% off",
    perNight: 187,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/Skagen.jpg",
      "/Images/hotels/Skagen1.jpg",
      "/Images/hotels/Skagen2.jpg",
      "/Images/hotels/noida.webp",
    ],

    name: "Green Valley Hotel",
    location: "Skagen",
    rating: 9.0,
    reviews: 40,
    label: "Excellent",
    originalPrice: 550,
    currentPrice: 467,
    discount: "15% off",
    perNight: 233,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/Aalborg.jpg",
      "/Images/hotels/Aalborg1.jpg",
      "/Images/hotels/Aarhus.jpg",
      "/Images/hotels/Odense1.jpg",
    ],

    name: "Seaside Comfort Inn",
    location: "Aalborg",
    rating: 8.7,
    reviews: 25,
    label: "Very Good",
    originalPrice: 480,
    currentPrice: 408,
    discount: "15% off",
    perNight: 204,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "Aurora Sky Lodge",
    location: "Nuuk",
    rating: 9.8,
    reviews: 12,
    label: "Exceptional",
    originalPrice: 890,
    currentPrice: 712,
    discount: "20% off",
    perNight: 356,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "Metro Central Hotel",
    location: "Frederiksberg",
    rating: 8.3,
    reviews: 19,
    label: "Good",
    originalPrice: 410,
    currentPrice: 369,
    discount: "10% off",
    perNight: 185,
    currency: "DKK",
  },
  {
    images: [
       "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "Royal Park Stay",
    location: "Roskilde",
    rating: 8.9,
    reviews: 37,
    label: "Excellent",
    originalPrice: 630,
    currentPrice: 525,
    discount: "17% off",
    perNight: 262,
    currency: "DKK",
  },
  {
    images: [
     "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "The Blue Marina",
    location: "Kolding",
    rating: 9.1,
    reviews: 21,
    label: "Excellent",
    originalPrice: 575,
    currentPrice: 488,
    discount: "15% off",
    perNight: 244,
    currency: "DKK",
  },
  {
    images: [
       "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "Hotel Hygge",
    location: "Helsingør",
    rating: 9.4,
    reviews: 29,
    label: "Exceptional",
    originalPrice: 690,
    currentPrice: 552,
    discount: "20% off",
    perNight: 276,
    currency: "DKK",
  },
  {
    images: [
     "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "Sunrise Comfort Hotel",
    location: "Næstved",
    rating: 8.4,
    reviews: 18,
    label: "Very,Good",
    originalPrice: 495,
    currentPrice: 420,
    discount: "15% off",
    perNight: 210,
    currency: "DKK",
  },
  {
    images: [
 "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],

    name: "Lakeside Suites",
    location: "Silkeborg",
    rating: 8.9,
    reviews: 35,
    label: "Excellent",
    originalPrice: 620,
    currentPrice: 527,
    discount: "15% off",
    perNight: 263,
    currency: "DKK",
  },
  {
    images: [
      "/Images/hotels/noida.webp",
      "/Images/hotels/noida1.webp",
      "/Images/hotels/noida3.webp",
      "/Images/hotels/noida4.avif",
    ],
    name: "Viking Retreat Hotel",
    location: "Randers",
    rating: 9.3,
    reviews: 26,
    label: "Exceptional",
    originalPrice: 710,
    currentPrice: 602,
    discount: "15% off",
    perNight: 301,
    currency: "DKK",
  },
];
